#!/usr/bin/env bash
set -eo pipefail
IFS=$'\n\t'

# Dependencies:
# sudo apt-get install gnupg-agent
# sudo apt-get install gnupg2

# Add this to .bash_profile or .profile:
# eval $(gpg-agent --daemon)
# source pw_autocomplete.sh in .bashrc

# Getting started
# touch passwords.txt
# mkdir -p ~/.passwords
# gpg --cipher-algo AES256 --output ~/.passwords/passwords.gpg --symmetric passwords.txt

PW_PATH=$HOME/.passwords
PASSWORDS_FILE=$PW_PATH/passwords.gpg

if [ $# -eq 0 ]; then
  echo "Usage: `basename $0` [file]"
  echo "  --change-password     change password and re-encrypt all files"
  exit 0
fi

if [ ! -f $PASSWORDS_FILE ]; then
  echo "$HOME/.passwords/passwords.gpg does not exist..."
  exit 0
fi

if [ "$1" == "--change-password" ]; then
  gpg2 --quiet --decrypt $PASSWORDS_FILE | gpg2 --cipher-algo AES256 --output $PASSWORDS_FILE.new --symmetric
  mv $PASSWORDS_FILE.new $PASSWORDS_FILE
else
  SEARCH=$1

  SITE=""
  USERNAME=""
  PASSWORD=""

  while read line; do
    if [[ "$line" == s:* ]]; then
      SITE=${line#s: }
    elif [[ "$line" == u:* ]]; then
      USERNAME=${line#u: }
    elif [[ "$line" == p:* ]]; then
      PASSWORD=${line#p: }
    else
      if [[ "$SITE" =~ $SEARCH ]]; then
	break
      else
	SITE=""
	USERNAME=""
	PASSWORD=""
      fi
    fi
  done < <(gpg2 --quiet --decrypt $PASSWORDS_FILE )

  echo "Press [u] to copy username or [p] to copy password"
  echo "site     = $SITE"
  echo "username = $USERNAME"
  echo "password = *****"
  read -n1 -r -s key
  if [ "$key" == "u" ]; then
    echo Copied username to clipboard...
    echo -n $USERNAME | xclip -selection c
  elif [ "$key" == "p" ]; then
    echo Copied password to clipboard...
    echo -n $PASSWORD | xclip -selection c
  fi
  exit 0

  echo SITE:$SITE
fi
