#!/usr/bin/env bash
set -eo pipefail
IFS=$'\n\t'

PASSWORDS_FILE=$HOME/passwords.gpg

if [ $# -eq 0 ]; then
  echo "Usage: `basename $0` [file]"
  echo "  --change-password          change password and re-encrypt password file"
  echo "  --create-password-file     create a new password file"
  exit 0
fi

function ensure_passwords_file_exists() {
  if [ ! -f $PASSWORDS_FILE ]; then
    echo "$HOME/.passwords/passwords.gpg does not exist..."
    exit 0
  fi
}

if [ "$1" == "--change-password" ]; then
  ensure_passwords_file_exists
  gpg2 --quiet --decrypt $PASSWORDS_FILE | gpg2 --cipher-algo AES256 --output $PASSWORDS_FILE.new --symmetric
  mv $PASSWORDS_FILE.new $PASSWORDS_FILE
elif [ "$1" == "--create-password-file" ]; then
  echo "" | gpg2 --cipher-algo AES256 --output $PASSWORDS_FILE --symmetric
else
  ensure_passwords_file_exists

  SEARCH="$@"

  SITE=""
  USERNAME=""
  PASSWORD=""

  while read line; do
    if [[ "$line" == s:* ]]; then
      SITE=${line#s: }
    elif [[ "$line" == u:* ]]; then
      USERNAME=${line#u: }
    elif [[ "$line" == p:* ]]; then
      PASSWORD=${line#p: }
    else
      if [[ "$SITE" =~ $SEARCH ]]; then
	break
      else
	SITE=""
	USERNAME=""
	PASSWORD=""
      fi
    fi
  done < <(gpg2 --quiet --decrypt $PASSWORDS_FILE )

  echo "Press [u] to copy username or [p] to copy password"
  echo "site     = $SITE"
  echo "username = $USERNAME"
  echo "password = *****"
  read -n1 -r -s key
  if [ "$key" == "u" ]; then
    echo Copied username to clipboard...
    echo -n $USERNAME | xclip -selection c
  elif [ "$key" == "p" ]; then
    echo Copied password to clipboard...
    echo -n $PASSWORD | xclip -selection c
  fi
  exit 0
fi
